CREATE TABLE IF NOT EXISTS user (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name TEXT
);

CREATE TABLE IF NOT EXISTS quiz (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name TEXT
);

CREATE TABLE IF NOT EXISTS question (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	content TEXT,
	quiz_id INTEGER REFERENCES quiz
);

CREATE TABLE IF NOT EXISTS choice (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	content TEXT,
	correct TINYINT(1),
	question_id INTEGER REFERENCES question
);

CREATE TABLE IF NOT EXISTS answer (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INTEGER REFERENCES user,
	question_id INTEGER REFERENCES question,
	choice_id INTEGER REFERENCES choice
);